root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/myapp"
  cmd = "go build -o ./tmp/myapp ./cmd/myapp"
  delay = 500
  exclude_dir = ["tmp", "bin", "dist", "logs"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go"]
  kill_delay = 500

[log]
  time = false

[misc]
  clean_on_exit = true
